# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'DormRoom' do

pod ‘Parse’
pod 'AWSS3'
pod 'SDWebImage'
pod 'UIActivityIndicator-for-SDWebImage'

end

target 'DormRoomTests' do

end

target 'DormRoomUITests' do

end

